name: Deploy to Amazon ECS fargate
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: app_cluster_3
  CONTAINER_NAME: app_3
  ECS_SERVICE: app_service_3
  ECS_TD: .github/workflows/td.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

     
