name: Deploy to Amazon ECS fargate
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: app_cluster_3
  CONTAINER_NAME: app_3
  ECS_SERVICE: app_service_3
  ECS_TD: .github/workflows/td.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: "ap-south-1"
      

     
