name: Deploy to Amazon ECS fargate
on:
  push:
    branches:
      - master
env:
  AWS_REGION: ap-south-1
  ECS_CLUSTER: app_cluster_3
  CONTAINER_NAME: app_3
  ECS_SERVICE: app_service_3
  #ECS_TD: .github/workflows/td.json

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: "ap-south-1"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform Init
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        run: terraform init

      - name: Terraform Apply
        id: terraform
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        run: |
          terraform apply -auto-approve
          
      - name: Download task definition
        run: aws ecs describe-task-definition --task-definition appv3 > task-definition.json

      - name: Display task definition
        run: cat task-definition.json

      - name: Wait for 1 minutes
        run: sleep 60
      
      - name: Terraform Destroy
        run: terraform apply -destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
